# CAR_RENTAL_COMPANY_CAR | CAR_ID , CAR_TYPE , DAILY_FEE, OPTIONS
# CAR_RENTAL_COMPANY_RENTAL_HISTORY | HISTORY_ID, CAR_ID, START_DATE, END_DATE
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN | PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE  * 30 *(100-COALESCE(D.DISCOUNT_RATE, 0))/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'

WHERE C.CAR_TYPE IN ('세단', 'SUV') 
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND ROUND(C.DAILY_FEE * 30 *(100 - D.DISCOUNT_RATE)/100)>= 500000
    AND ROUND(C.DAILY_FEE * 30 *(100 - D.DISCOUNT_RATE)/100) < 2000000
ORDER BY
    FEE DESC,
    C.CAR_TYPE,
    C.CAR_ID DESC;