# FIRST_HALF - SHIPMENT_ID, FLAVOR(JULY 외래키 값), TOTAL_ORDER
# JULY - SHIPMENT_ID, FLAVOR, TOTAL_ORDER

SELECT F.FLAVOR
FROM FIRST_HALF AS F 
JOIN JULY AS J ON F.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(J.TOTAL_ORDER) + SUM(F.TOTAL_ORDER) DESC
LIMIT 3;